#ifndef MCAL_TIMER_TIMER_CFG_H_
#define MCAL_TIMER_TIMER_CFG_H_

// Timer0 MODEs
#define TIMER0_MODE_NORMAL			0
#define TIMER0_MODE_CTC				1
#define TIMER0_MODE_PWM_FAST		2
#define TIMER0_MODE_PWM_PHASE		3

#define TIMER0_MODE_SELECT TIMER0_MODE_CTC


// Timer 0 Pre-Scaler
#define TIMER0_PRESCALER_NO_CLOCK			0
#define TIMER0_PRESCALER_NO_NOPRESCALING	1
#define TIMER0_PRESCALER_8					2
#define TIMER0_PRESCALER_64					3
#define TIMER0_PRESCALER_256				4
#define TIMER0_PRESCALER_1024				5

#define TIMER0_PRESCALER_EXTERNAL_FALING	6
#define TIMER0_PRESCALER_EXTERNAL_RISING	7

// Enable Interrupt
#define TIMER0_OVF_INTERRUPT 0
#define TIMER0_OCR_INTERRUPT 1

#define TIMER0_PRESCALER_SELECT TIMER0_PRESCALER_1024
// Timer Initial Value
#define TIMER0_TCNT0		0




#endif
